---
# This playbook installs and (re)configures Postgres.
- name: update apt-cache
  apt: update_cache=yes

- name: Ensure locale is available
  locale_gen: name=en_US.UTF-8

- name: install Postgres, its headers, and psycopg2
  apt: pkg={{ item }} state=installed
  with_items:
    - postgresql
    - python3-psycopg2

- name: Copy in pg_hba.conf
  template:
    src: templates/pg_hba.conf.jinja2
    dest: /etc/postgresql/10/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0640
  when:
    ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Copy in pgpass
  template:
    src: templates/pgpass.conf.jinja2
    dest: "/home/{{ LINUX_USER }}/.pgpass"
    owner: "{{ LINUX_USER }}"
    mode: 0600

- name: Restart postgres
  sudo: yes
  command: "service postgresql restart"

- name: add the database user
  become: true
  become_user: postgres
  postgresql_user:
    name={{ DB_USER }}
    password={{ DB_PASSWORD }}
    encrypted=yes

- name: create the database
  become: true
  become_user: postgres
  postgresql_db:
    name={{ DB_NAME }}
    owner={{ DB_USER }}
    template=template0
    encoding='UTF-8'
    lc_collate='en_US.UTF-8'
    lc_ctype='en_US.UTF-8'
    template='template0'
    state=present
